### ISSUE TITLE
Unregistered Model

### ISSUE THREAD

**Issue by adrianrdzv** [sampsyo/wideq#10]
I can retrieve the device current status but no command currently works because of the following error:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/smartthinq.py", line 162, in set_operation_mode
    self.turn_off()
  File "/config/custom_components/climate/smartthinq.py", line 194, in turn_off
    self._ac.set_on(False)
  File "/config/deps/lib/python3.6/site-packages/wideq.py", line 923, in set_on
    self._set_control('Operation', op_value)
  File "/config/deps/lib/python3.6/site-packages/wideq.py", line 755, in _set_control
    {key: value},
  File "/config/deps/lib/python3.6/site-packages/wideq.py", line 372, in set_device_controls
    'data': '',
  File "/config/deps/lib/python3.6/site-packages/wideq.py", line 296, in post
    return lgedm_post(url, data, self.auth.access_token, self.session_id)
  File "/config/deps/lib/python3.6/site-packages/wideq.py", line 137, in lgedm_post
    raise APIError(code, message)
wideq.APIError: ('0011', '등록되지 않은 모델입니다.')
```

Which translates to "Unregistered model"
I'm guessing is a localization issue with the model of AC I have: AC RAC_056905_MX

Any way to fix this?

**Comment by sampsyo** [comment]
Weird! I've never seen this error before. I'm not sure what to recommend—I got the current set of commands by digging around in the partially-obfuscated source code for the Cordova-based mobile SmartThinQ app; if you're feeling very intrepid, you might consider doing some of that too.

**Comment by adrianrdzv** [comment]
After several tries the problem was gone. I didn't change anything. Maybe it was my model was doing request and later was "identified". Not sure what was the issue.

**Comment by sampsyo** [comment]
This is truly mysterious API!
