### ISSUE TITLE
NameError Example.py

### ISSUE THREAD

**Issue by stingone** [sampsyo/wideq#111]
Hi.

After receiving the token and device number resulting in a wideq_state.json file when running the ac-mon command i get the error below. Any ideas how to fix this?

```
Traceback (most recent call last):
  File "example.py", line 235, in <module>
    main()
  File "example.py", line 231, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 191, in example
    example_command(client, cmd, args)
  File "example.py", line 167, in example_command
    func(client, *args)
  File "example.py", line 81, in ac_mon
    ac.monitor_start()
  File "/home/pi/wideq/wideq/client.py", line 455, in monitor_start
    mon.start()
  File "/home/pi/wideq/wideq/client.py", line 33, in start
    self.work_id = self.session.monitor_start(self.device_id)
  File "/home/pi/wideq/wideq/core_v2.py", line 305, in monitor_start
    'workId': gen_uuid(),
  File "/home/pi/wideq/wideq/core_v2.py", line 277, in post
    return lgedm_post(url, data, self.auth.access_token, self.session_id)
NameError: name 'lgedm_post' is not defined
```

**Comment by sampsyo** [comment]
Hello! I don't think you are using this repository, at least on the default branch—we do not have a file called `core_v2.py`.

**Comment by stingone** [comment]
It's comming from the V2 api https://github.com/gladhorn/wideq this is the only one where i get a device ID. if i you the original one. it creates a wideq_state.json but nothing happens.. at the and of the file i see the the country is default set on US instead of NL :(

**Comment by sampsyo** [comment]
That's a different repository, though. The people working on this repository can't help with problems you are having with code we did not write.

I think that repo is an in-progress fork, however, and not yet ready to actually work.
