### ISSUE TITLE
No devices are shown/listed

### ISSUE THREAD

**Issue by jbmorgado** [sampsyo/wideq#117]
I tried a new setup.

- Deleted the old account using Google for authentication (first I removed all devices).
- Created a new account using email/pass
- Got the authentication token
- I tried with only one device added in my LG account, and then with 3 (they are all AC units).

Still, I can't get any device listed:
```
bash-5.0# python3 example.py -c PT -l en-US ls -v
2020-08-04 19:01:37 DEBUG [wideq.example] State file found '/root/temp/wideq/wideq_state.json'
2020-08-04 19:01:37 DEBUG [wideq.example] State file found '/root/temp/wideq/wideq_state.json'
2020-08-04 19:01:38 DEBUG [wideq.example] Wrote state file '/root/temp/wideq/wideq_state.json'
2020-08-04 19:01:38 DEBUG [wideq.example] Wrote state file '/root/temp/wideq/wideq_state.json'
bash-5.0# python3 example.py -c PT -l en-US ls -v
2020-08-04 19:01:45 DEBUG [wideq.example] State file found '/root/temp/wideq/wideq_state.json'
2020-08-04 19:01:45 DEBUG [wideq.example] State file found '/root/temp/wideq/wideq_state.json'
2020-08-04 19:01:46 DEBUG [wideq.example] Wrote state file '/root/temp/wideq/wideq_state.json'
2020-08-04 19:01:46 DEBUG [wideq.example] Wrote state file '/root/temp/wideq/wideq_state.json'
```

**Comment by barbetb** [comment]
I have exactly the same problem. Authentication worked with regular Lg account. No devices are shown.

**Comment by lvlie** [comment]
I think you are probably running into the issue that this is trying to fix:
https://github.com/sampsyo/wideq/pull/100

Basically: newer units and/or newer accounts can only use v2 of the API, that wideq doesnt support yet.

**Comment by JasperE84** [comment]
Having the same problem while trying to setup my newly installed LG AC on a new LG account.

**Comment by jacekpaszkowski** [comment]
Same here :( Hope there will be a working version soon

**Comment by lvlie** [comment]
I did get wideq to show my devices with branch api2_merged from this fork: https://github.com/gladhorn/wideq.git 
However, I cannot get the custom integration to pick this up. I have both git repo's checked out to my custom_components dir, but the wideq one is probably in the wrong location?

**Comment by jacekpaszkowski** [comment]
@lvlie yes, i confirm that wideq version from that repo lists my devices. I'll try to use it in HA

**Comment by JasperE84** [comment]
> @lvlie yes, i confirm that wideq version from that repo lists my devices. I'll try to use it in HA

That doesn't seem to work, I tried forcing the wideq from gladhorn, resulted in:

`Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/username/.homeassistant/custom_components/smartthinq/__init__.py", line 79, in setup
    client = wideq.Client.from_token(refresh_token, region, language)
  File "/home/username/.homeassistant/custom_components/wideq_fork/wideq/client.py", line 215, in from_token
    client._auth = core.Auth(client.gateway, None, refresh_token)`

core.Auth def in gladhorns repo:
`class Auth(object):
    def __init__(self, gateway, oauth_url, access_token, refresh_token):`

Looks like its missing a parameter

**Comment by jacekpaszkowski** [comment]
@JasperE84 thank you for your test. It seems that The code od not ready for HA. But at least it is possible to interact with V2 API.
Could you tell me how you managed to override wideq in HA. I have my HA on RPi.

**Comment by JasperE84** [comment]
Check 

> @JasperE84 thank you for your test. It seems that The code od not ready for HA. But at least it is possible to interact with V2 API.
> Could you tell me how you managed to override wideq in HA. I have my HA on RPi.

Check out https://askubuntu.com/a/471168/568023

**Comment by barbetb** [comment]
So with the gladhorn fork I can list my AC, but not give any instructions to the AC.

**Comment by JasperE84** [comment]
On the cmdline yes. In home assistent no. The Thinq custom component will crash upon loading in hass. (After sensor/components are found and registered I think it tried setting up sensor monitoring which failed because of a missing edmpost method.) 
Fingers crossed @sampsyo, maybe with help from  @ollo69 will get the of API v2 to work.

**Comment by brunomgsousa** [comment]
Hi, I have an old account with 2 old Mural AC's and all works good, but today a installed a new AC at my home and i added this new device on my account. The new AC is not listed in the wideq only the old's 2 AC's. Is possible that in the same account 2 devices use the v1API and the new use v2 API ? Tks in advance.
