### ISSUE TITLE
Error trying to turn AC off

### ISSUE THREAD

**Issue by RMCob** [sampsyo/wideq#17]
Getting the AC device ID worked ok, but I get the following error when trying to turn the AC on/off. None of the other device commands seem to work either but I thought I'd start here:
$ python3 example.py turn off d27bdb00-7149-11d3-80b0-2c2bf923c76c 
Traceback (most recent call last):
  File "example.py", line 203, in <module>
    main()
  File "example.py", line 199, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 163, in example
    example_command(client, cmd, args)
  File "example.py", line 139, in example_command
    func(client, *args)
  File "example.py", line 113, in turn
    ac = wideq.ACDevice(client, client.get_device(device_id))
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 778, in __init__
    self.model = client.model_info(device)
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 608, in model_info
    url = device.model_info_url
AttributeError: 'NoneType' object has no attribute 'model_info_url'
$

**Comment by sampsyo** [comment]
The arguments go in the other order. :smiley: Try:

```
$ python3 example.py turn d27bdb00-7149-11d3-80b0-2c2bf923c76c off
```

I've just pushed a change that will emit a useful error message when this happens.

**Comment by RMCob** [comment]
Thanks! That worked.
