### ISSUE TITLE
Error with ac-config

### ISSUE THREAD

**Issue by RMCob** [sampsyo/wideq#19]
Got the following error when trying ac-config:

$ python3 example.py ac-config d27bdb00-7149-11d3-80b0-2c2bf923c76c 
Session expired.
{'UseTime': '0', 'ChangePeriod': '720', 'ChangeDate': '00000000'}
{'RemainTime': '205', 'ChangePeriod': '250'}
{'Month': '0', 'Day': '0', 'Week': '0'}
Traceback (most recent call last):
  File "example.py", line 203, in <module>
    main()
  File "example.py", line 199, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 163, in example
    example_command(client, cmd, args)
  File "example.py", line 139, in example_command
    func(client, *args)
  File "example.py", line 122, in ac_config
    print(ac.get_volume())
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 981, in get_volume
    value = self._get_control('SpkVolume')
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 808, in _get_control
    'Control',
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 398, in get_device_config
    'data': '',
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 306, in post
    return lgedm_post(url, data, self.auth.access_token, self.session_id)
  File "/home/pi/Desktop/wideq-1.0.1/wideq.py", line 140, in lgedm_post
    raise APIError(code, message)
wideq.APIError: ('0100', '실패')

What does "SpkVolume" have to do with an A/C? Just curious :-)

**Comment by sampsyo** [comment]
As with everything else in wideq, it's based on trial and error with my own AC unit. Mine seems to have a parameter like that, but I have no idea what it does (because it doesn't seem to be possible to change it). Maybe it controls the volume of the "bing" noises it makes whenever a setting is changed?

**Comment by dacrypt** [comment]
I'm copying my results here using the latest version. This might give you a better idea why is failing with some other models.

```
% python3 example.py -c BR -l pt-BR ac-config d27c7740-7149-11d3-10b4-7440be9deeb2
Session expired.
Traceback (most recent call last):
  File "example.py", line 251, in <module>
    main()
  File "example.py", line 247, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 195, in example
    example_command(client, cmd, args)
  File "example.py", line 171, in example_command
    func(client, *args)
  File "example.py", line 146, in ac_config
    print(ac.get_filter_state())
  File "/Users/david/dev/dacrypt/wideq/wideq/ac.py", line 239, in get_filter_state
    return self._get_config('Filter')
  File "/Users/david/dev/dacrypt/wideq/wideq/client.py", line 442, in _get_config
    data = self.client.session.get_device_config(
  File "/Users/david/dev/dacrypt/wideq/wideq/core.py", line 395, in get_device_config
    res = self.post('rti/rtiControl', {
  File "/Users/david/dev/dacrypt/wideq/wideq/core.py", line 303, in post
    return lgedm_post(url, data, self.auth.access_token, self.session_id)
  File "/Users/david/dev/dacrypt/wideq/wideq/core.py", line 144, in lgedm_post
    raise APIError(code, message)
wideq.core.APIError: ('0011', '등록되지 않은 모델입니다.')

```
I turned it off and trying again, I got:

```
% python3 example.py -c BR -l pt-BR ac-config d27c7740-7149-11d3-10b4-7440be9deeb2
{'UseTime': '310', 'ChangePeriod': '720', 'ChangeDate': '00000000'}
{'RemainTime': '0', 'ChangePeriod': '0'}
{'Day': '0', 'Week': '0', 'Month': '0'}
0
Traceback (most recent call last):
  File "example.py", line 251, in <module>
    main()
  File "example.py", line 247, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 195, in example
    example_command(client, cmd, args)
  File "example.py", line 171, in example_command
    func(client, *args)
  File "example.py", line 150, in ac_config
    print(ac.get_light())
  File "/Users/david/dev/dacrypt/wideq/wideq/ac.py", line 255, in get_light
    value = self._get_control('DisplayControl')
  File "/Users/david/dev/dacrypt/wideq/wideq/client.py", line 450, in _get_control
    data = self.client.session.get_device_config(
  File "/Users/david/dev/dacrypt/wideq/wideq/core.py", line 395, in get_device_config
    res = self.post('rti/rtiControl', {
  File "/Users/david/dev/dacrypt/wideq/wideq/core.py", line 303, in post
    return lgedm_post(url, data, self.auth.access_token, self.session_id)
  File "/Users/david/dev/dacrypt/wideq/wideq/core.py", line 142, in lgedm_post
    raise API_ERRORS[code](code, message)
wideq.core.FailedRequestError: ('0100', '실패')
```
