### ISSUE TITLE
error when starting example.py 

### ISSUE THREAD

**Issue by izharm** [sampsyo/wideq#41]
Hi,

I am trying to run example.py for the first time, I think the authentication was successful since I get a URL with tokens, however when I paste the URL back I get the following error:

Traceback (most recent call last):
  File "example.py", line 225, in <module>
    main()
  File "example.py", line 221, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 181, in example
    example_command(client, cmd, args)
  File "example.py", line 157, in example_command
    func(client, *args)
  File "example.py", line 26, in ls
    for device in client.devices:
  File "D:\Python37\apps\wideq-master\wideq\client.py", line 123, in devices
    self._devices = self.session.get_devices()
  File "D:\Python37\apps\wideq-master\wideq\client.py", line 114, in session
    self._session, self._devices = self.auth.start_session()
  File "D:\Python37\apps\wideq-master\wideq\core.py", line 275, in start_session
    self.gateway.country, self.gateway.language)
  File "D:\Python37\apps\wideq-master\wideq\core.py", line 193, in login
    return lgedm_post(url, data)
  File "D:\Python37\apps\wideq-master\wideq\core.py", line 133, in lgedm_post
    raise APIError(code, message)
wideq.core.APIError: ('0010', '데이터가 존재하지 않습니다.')

any suggestions ?

thanks,

**Comment by Cortex33** [comment]
Easy fix to that on debian (work on Ubuntu too, perhaps on all other linux distro).
sudo nano /etc/ssl/openssl.cnf
Search and replace :
MinProtocol = TLSv1.X
by
MinProtocol = TLSv1.0

Restart your server, follow the process to install wideq, everything will work fine.

**Comment by sampsyo** [comment]
On the other hand, such a global configuration change might be undesirable---it lets your machine use older, less secure protocols to connect to _any_ server.

**Comment by Cortex33** [comment]
Because of old configuration in some LG server especially in France :), but not only it seam. I had no choice but this one to make it work.
If someone find a more secure way, please share.

**Comment by tayanov** [comment]
> Easy fix to that on debian (work on Ubuntu too, perhaps on all other linux distro).
> sudo nano /etc/ssl/openssl.cnf
> Search and replace :
> MinProtocol = TLSv1.X
> by
> MinProtocol = TLSv1.0
> 
> Restart your server, follow the process to install wideq, everything will work fine.

My debian 10 not have  sting MinProtocol = TLSv1.0 at /etc/ssl/openssl.cnf

**Comment by Cortex33** [comment]
if you have the conf file, just add the parameter if you have issue to use example.py, if not dont change anything.

**Comment by paoloantinori** [comment]
I'm facing the same issue on Fedora 31 and an LG Italian account, but I've not been able to bypass the problem with `update-crypto-policies --set LEGACY` that supposedly should whitelist `TLSv1.0`. Any idea?

**Comment by tayanov** [comment]
Change all request ( ... ) To request (... , verify=false) . Or wait when lg repair. Im wait In russia. now ok.

**Comment by paoloantinori** [comment]
I've added `verify=False` to all the 3 `requests` invocations that I have found but it's still failing with the same error. I'm starting suspecting this not being related to TLS
