### ISSUE TITLE
HomeBridge and Docker Issue 

### ISSUE THREAD

**Issue by kaiatkins** [sampsyo/wideq#58]
am using oznu/docker-homebridge with homebridge UI enabled on Western Digital PR4100

the error I am getting when home bridge loads:

[8/28/2019, 10:35:23 AM] Homebridge is running on port 53998.
Traceback (most recent call last):
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 1, in
import wideq
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/init.py", line 3, in
from .core import * # noqa
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in
import requests
ModuleNotFoundError: No module named 'requests'

Here is python3 version:
Hello I am trying to use the wideq with this bundle but keep getting error when execute 

/homebridge/node_modules/homebridge-lg-airco/resources/wideq # python3 --version
Python 3.7.3

When running command: python3 example.py -c “US” -l “en-US” -s "wideq_state.json" ls

/homebridge/node_modules/homebridge-lg-airco/resources/wideq # python3 example.py -c “US” -l “en-US” -s "wideq_state.json" ls
Traceback (most recent call last):
File "example.py", line 1, in
import wideq
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/init.py", line 3, in
from .core import * # noqa
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in
import requests
ModuleNotFoundError: No module named 'requests'

**Comment by sampsyo** [comment]
Please follow the setup instructions to install wideq along with its dependencies.
