### ISSUE TITLE
ac-config works partially (JSONDecodeError)

### ISSUE THREAD

**Issue by alpe12** [sampsyo/wideq#84]
Probably same (or related) to https://github.com/sampsyo/wideq/issues/64 and many others.
But while others fail at start, mine returns some results right.

```
$ python3 example.py -c BR -l pt-BR ac-config d27f5d70-7149-11d3-80c7-7440bec36c49
2020-02-09 14:45:20 INFO [wideq.example] Session expired.
{'UseTime': '43', 'ChangePeriod': '720', 'ChangeDate': '00000000'}
{'RemainTime': '0', 'ChangePeriod': '0'}
{'Day': '0', 'Week': '0', 'Month': '0'}
413  watts
0  watts
0
True
Traceback (most recent call last):
  File "example.py", line 269, in <module>
    main()
  File "example.py", line 265, in main
    example(args.country, args.language, args.verbose, args.cmd, args.args)
  File "example.py", line 206, in example
    example_command(client, cmd, args)
  File "example.py", line 175, in example_command
    func(client, *args)
  File "example.py", line 156, in ac_config
    print(ac.get_zones())
  File "/media/alpe/42e85415-2b13-4e65-bff6-e01945d9ea67/temp/wideq/wideq/ac.py", line 198, in get_zones
    return self._get_config('DuctZone')
  File "/media/alpe/42e85415-2b13-4e65-bff6-e01945d9ea67/temp/wideq/wideq/client.py", line 435, in _get_config
    return json.loads(base64.b64decode(data).decode('utf8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by sampsyo** [comment]
Hi! Yes, I think this is the same as #64. :smiley:
